[settings.github]
github_attestations = false

[tools."http:helm"]
# renovate: datasource=github-releases depName=helm/helm
version = "4.0.4"

[tools."http:helm".platforms]
linux-x64 = { url = "https://get.helm.sh/helm-v{version}-linux-amd64.tar.gz" }
linux-arm64 = { url = "https://get.helm.sh/helm-v{version}-linux-arm64.tar.gz" }
macos-arm64 = { url = "https://get.helm.sh/helm-v{version}-darwin-arm64.tar.gz" }
